Develop
ianinadavydova/KeywordSearcher pull request #1
Opened 2019-04-08 19:25 UTC by ianinadavydova

BinaryKeywordSearcher and TextKeywordSearcher implemented
Tests added

2019-04-15 20:51 UTC, AnnaS91 requested changes

2019-04-15 20:51 UTC, AnnaS91 commented on .gitignore
> +.idea/vcs.xml
лучше в гитигнор добавлять всё содержимое папки .idea

2019-04-15 20:51 UTC, AnnaS91 commented on src/main/java/BinaryKeywordSearcher.java
> +    private static void recognizeWord(HashMap<String, Integer> countedKeywords, StringBuilder wordStringBuilder) {
в качестве типа параметра лучше объявлять наиболее широкую коллекцию (в данном случае Map)

2019-04-15 20:51 UTC, AnnaS91 commented on src/main/java/BinaryKeywordSearcher.java
> +        FileInputStream fileInput = new FileInputStream(inputFile);
пересмотрите, пожалуйста, ещё раз лекцию по IOStreams. Мы обсуждали, что потоки обязательно надо закрывать. Делать это просто в конце метода нельзя, потому что в случае выпадения ошибки, вы останетесь с открытым потоком. Поэтому либо нужно оборачивать код в try-with-resources (предпочтительнее), либо вызывать close в блоке finally

2019-04-15 20:51 UTC, AnnaS91 commented on src/main/java/BinaryKeywordSearcher.java
> +        HashMap<String, Integer> countedKeywords = new HashMap<String, Integer>();
при объявлении тоже лучше использовать наиболее широкую из коллекций: Map<String, Integer> ... = new HashMap<>(); в конструкторе параметры дженерика подставит за Вас компилятор, их можно опустить

2019-04-15 20:51 UTC, AnnaS91 commented on src/main/java/BinaryKeywordSearcher.java
> +        FileOutputStream outputFileStream = new FileOutputStream(inputFile + ".searchKeywords");
запись в файл можно было вынести в отдельный метод

2019-04-15 20:51 UTC, AnnaS91 commented on src/main/java/TextKeywordSearcher.java
> +        HashMap<String, Integer> countedKeywords = new HashMap<String, Integer>();
аналогично

2019-04-15 20:51 UTC, AnnaS91 commented on src/main/java/TextKeywordSearcher.java
> +                if (SourceVersion.isKeyword(word)) {
это можно было бы вынести как метод в какой-нибудь класс, который бы использовали оба Ваших класса, чтобы не создавать дубликаты кода

2019-04-15 20:51 UTC, AnnaS91 commented on src/main/java/TextKeywordSearcher.java
> +        inputBufferedReader.close();
аналогичное замечание про закрытие

2019-04-15 20:51 UTC, AnnaS91 commented on src/main/java/TextKeywordSearcher.java
> +        PrintWriter outputWriter = new PrintWriter(inputFile + ".searchKeywords");
аналогично - отдельный метод

2019-04-15 20:51 UTC, AnnaS91 commented on src/test/java/BinaryKeywordSearcherTest.java
> +    private static boolean areFilesEqual(BufferedReader result, BufferedReader correct) throws IOException {
private методы принято располагать в конце класса, для тестов действует такое же правило

2019-04-15 20:51 UTC, AnnaS91 commented on src/test/java/BinaryKeywordSearcherTest.java
> +                if (!resultString.equals(correctString))
а почему здесь просто не вернуть resultString.equals(correctString) ?

2019-04-15 20:51 UTC, AnnaS91 commented on src/test/java/TextKeywordSearcherTest.java
> +    private static boolean areFilesEqual(BufferedReader result, BufferedReader correct) throws IOException {
лучше было бы создать тестовый вспомогательный класс, чем дублировать код

2019-04-17 18:11 UTC, ianinadavydova commented on src/main/java/BinaryKeywordSearcher.java
> +    private static void recognizeWord(HashMap<String, Integer> countedKeywords, StringBuilder wordStringBuilder) {
Исправила

2019-04-17 18:25 UTC, ianinadavydova commented on src/main/java/BinaryKeywordSearcher.java
> +        FileInputStream fileInput = new FileInputStream(inputFile);
Исправила

2019-04-17 18:26 UTC, ianinadavydova commented on src/main/java/BinaryKeywordSearcher.java
> +        HashMap<String, Integer> countedKeywords = new HashMap<String, Integer>();
Исправила

2019-04-17 18:26 UTC, ianinadavydova commented on src/main/java/BinaryKeywordSearcher.java
> +        FileOutputStream outputFileStream = new FileOutputStream(inputFile + ".searchKeywords");
Исправила

2019-04-17 18:27 UTC, ianinadavydova commented on src/main/java/TextKeywordSearcher.java
> +        HashMap<String, Integer> countedKeywords = new HashMap<String, Integer>();
Исправила

2019-04-17 18:30 UTC, ianinadavydova commented on src/main/java/TextKeywordSearcher.java
> +                if (SourceVersion.isKeyword(word)) {
Вынесла в `KeywordUtil.recognizeWord`

2019-04-17 18:31 UTC, ianinadavydova commented on src/main/java/TextKeywordSearcher.java
> +        inputBufferedReader.close();
Исправила

2019-04-17 18:31 UTC, ianinadavydova commented on src/main/java/TextKeywordSearcher.java
> +        PrintWriter outputWriter = new PrintWriter(inputFile + ".searchKeywords");
Исправила

2019-04-17 18:32 UTC, ianinadavydova commented on src/test/java/BinaryKeywordSearcherTest.java
> +    private static boolean areFilesEqual(BufferedReader result, BufferedReader correct) throws IOException {
Исправила

2019-04-17 18:50 UTC, ianinadavydova commented on src/test/java/BinaryKeywordSearcherTest.java
> +                if (!resultString.equals(correctString))
Использовала `Objects.equals(resultString, correctString)`

2019-04-17 18:52 UTC, ianinadavydova commented on src/test/java/TextKeywordSearcherTest.java
> +    private static boolean areFilesEqual(BufferedReader result, BufferedReader correct) throws IOException {
Исправила

2019-04-17 19:00 UTC, ianinadavydova commented on .gitignore
> +.idea/vcs.xml
Добавила

2019-04-18 11:03 UTC, AnnaS91 requested changes

2019-04-18 11:03 UTC, AnnaS91 commented on src/main/java/BinaryKeywordSearcher.java
> +    private static void writeResult(List<Map.Entry<String, Integer>> items, String path) throws IOException {
а почему просто Map не использовали? если нужна была сортировка, можно было бы использовать TreeMap

2019-04-18 11:03 UTC, AnnaS91 commented on src/test/java/AbstractKeywordSearcherTest.java
> +    public void Dot() throws IOException {
методы называем с маленькой буквы

2019-04-18 15:45 UTC, ianinadavydova commented on src/main/java/BinaryKeywordSearcher.java
> +    private static void writeResult(List<Map.Entry<String, Integer>> items, String path) throws IOException {
Я не использовала TreeMap, потому что TreeMap сортирует по ключу, а я хотела отсортировать ключевые слова не по ключу, а по значению и выводить их в файл таким образом, чтобы первым было самое часто встречающееся слово

2019-04-18 15:59 UTC, AnnaS91 commented on src/main/java/BinaryKeywordSearcher.java
> +    private static void writeResult(List<Map.Entry<String, Integer>> items, String path) throws IOException {
Ясно. Но в таком случае лучше было бы всё-равно передать map, а перед записью в файл собирать строку, например, с помощью Stream API (потому что лист из Entry для map немного странно передавать). Но это как идея для рефакторинга, задание зачтено

2019-04-18 15:59 UTC, AnnaS91 approved these changes

2019-06-23 19:58 UTC, merged